### ISSUE TITLE
Hardening transforming on segmentation is slow if master representation is planar contours

### ISSUE THREAD

**Issue by lassoan** [SlicerRt/SlicerRT#102]
How to reproduce:
- Load segmentation
- Create new Linear Transform
- Set LR shift of 5 mm (any shift causes the issue)
- Apply the transform to the ‘13 RTSTRUCT PT_MidTreat’ node
- Click ‘Harden Transform’ button

Harden takes several minutes instead of just a few seconds.

See details here: https://discourse.slicer.org/t/harden-transform-on-large-segmentation-hangs-3d-slicer/5643/7

Sample data set:
https://unioxfordnexus-my.sharepoint.com/:u:/g/personal/donc0432_ox_ac_uk/EWFRKBv6xYZLuHqmtEkvwR4Bn9vKHM0AJFlCh9wNLMHDsw?e=YQiLwa

**Comment by cpinter** [comment]
We observed that this only happens if the closed surface representation is visible (not sure if 2D or 3D is the reason).
A possible solution is to use DisableModified in the ApplyTransform function in the segmentation node.

**Comment by cpinter** [comment]
Fixed in commit https://github.com/Slicer/Slicer/commit/3195e6d0bcd3ef29e383294a9b4e7ba13dfa9469
