### ISSUE TITLE
Many warnings in planar contour to closed surface conversion

### ISSUE THREAD

**Issue by cpinter** [SlicerRt/SlicerRT#103]
A warning is logged many times and pollutes the output

Warning: In C:\d\S4R\VTK\Common\DataModel\vtkPolyData.cxx, line 993
vtkPolyData (0000022C698427F0): Building VTK_LINE 1 with only one point, but VTK_LINE needs at least two points. Check the input.

Can be reproduced for sure with the dataset from the issue https://github.com/SlicerRt/SlicerRT/issues/102

**Comment by Sunderlandkyl** [comment]
During the end cap decimation, some lines were decimated to < 2 points.
Fixed in 2f2920a,

**Comment by cpinter** [comment]
Awesome, thank you!
