### ISSUE TITLE
Distinguish two ROIs with same Name but different Number.

### ISSUE THREAD

**Issue by GiulioBen** [SlicerRt/SlicerRT#110]
Dear all, i have a problem that i'm not able to solve by myself. 

I want to import a RT Structure containing 2 different ROI with the same (3006,0026)ROIName = "Lesion01" but with a different (3006,0022)ROINumber = {1, 2}.

When I import it I'm no more able to distinguish them, neither in the Data nor in the Segmentation module. The Name is the same, the Number is not reported at all. 

I've tried to understand if the first one always has ROINumber = 1 whereas the second one is the ROINumber=2 but I can't find the block of code.

Can someone help me to distinguish the two segments? Thank you!!

<img width="555" alt="Screenshot 2019-07-08 at 15 23 45" src="https://user-images.githubusercontent.com/38356385/60813638-73b53d00-a194-11e9-80e3-35ccaef294b9.png">

**Comment by cpinter** [comment]
Interesting problem indeed.

What I'd do is I'd set the ROINumber as a tag to the segment. Then if you hover the segment in the Data module then the ROINumber will be included in the tooltip.

It's only one line of code. I can do it for you today or tomorrow if you'd like.

**Comment by GiulioBen** [comment]
It's my first approach to Slicer and Python, but I've already coded in C++ or vb. Indeed I was looking  for a way to concatenate ROINumber + "-" + ROIName in the segmentation name, but maybe the tag is a smarter way.

I'd really appreciate your help, maybe I'll also learn hot to use Slicer!
Best.

**Comment by cpinter** [comment]
I implemented the change, it is supposed to be available in tomorrow's Slicer preview version. It was more than a line of code doing it right, but it took only a few minutes :)

This is how the ROI number appears:
![image](https://user-images.githubusercontent.com/1325980/60819992-8c126100-a16e-11e9-8517-6cb572bc7d78.png)

I hope this is fine.

**Comment by GiulioBen** [comment]
Thank you master. 
Tomorrow I'll let you know if it works!

Best

**Comment by GiulioBen** [comment]
At the moment in the repository I find only three versions of 
Slicer-4.11.0-2019-07-06-win-amd64.exe
It seems that the new code has not been compiled, indeed there is no trace of the ROINumber neither in Slicer-4.11.0-2019-07-06-win-amd64.exe nor in Slicer-4.11.0-2019-07-06-win-amd64.exe (2).

Let me know! Best regards.

**Comment by GiulioBen** [comment]
**Works like a charm!!**

**Thank you boss!**
