### ISSUE TITLE
Gamma dose comparison should allow sub-voxel search

### ISSUE THREAD

**Issue by gregsharp** [SlicerRt/SlicerRT#111]
The gamma dose comparison should allow sub-voxel search, and that choice should be enabled by default.  The necessary line of code to enable sub-voxel search is:

gamma->set_interp_search (true);

**Comment by cpinter** [comment]
Thanks for adding this ticket!

Could you please provide me some text that I can as the tooltip? I think it's important to describe exactly what it interpolates, especially that the same checkbox is repurposed.
Thanks!

**Comment by kmalexander5** [comment]
Thanks Greg and Csaba!  

I think the 'Use linear interpolation' checkbox (calling resample-nn) should be eliminated all together.  
For the new checkbox to enable the sub-voxel search, maybe we should use the same terminology as the Ju et al 2008 paper.  Checkbox can be labelled 'Use geometric gamma calculation' or something like that.  

The tooltip could read:
"By checking this box, gamma will be calculated according to Ju et al 2008, which finds the point with the minimum gamma value by using the normal vector between the two candidate points."

**Comment by cpinter** [comment]
Thanks, @kmalexander5 !
I agree, I repurposed the old linear interpolation checkbox for the interp_search function.
So we don't want to mention interpolation at all? It seems odd considering the name of the Plastimatch function.

**Comment by kmalexander5** [comment]
True @cpinter, but the paper is actually titled 'Geometric interpretation of the gamma dose distribution comparison technique:  Interpolation-free calculation'.  So adding in the word interpolation to the check box might seem odd!

**Comment by cpinter** [comment]
OK so it seems that the Plastimatch function name is misleading a bit.

Anyway, I'll make these changes then. Thanks!

**Comment by kmalexander5** [comment]
What do you think @gregsharp?

**Comment by cpinter** [comment]
Should it be on by default?

**Comment by cpinter** [comment]
I added the option
![image](https://user-images.githubusercontent.com/1325980/61073683-f41dad00-a3e3-11e9-9ea0-36d3d0b44e7a.png)
It is on by default.

Please test it in tomorrow's preview build and close ticket if works as expected.

**Comment by kmalexander5** [comment]
Awesome - just seeing these now.  Thanks @cpinter!

Either way - unchecked or checked is fine.  I'd tend to suggest to leave it off by default so the user can make a conscious decision to use it.  

I imagine I won't be able to do a proper test until the back-end that is resampling the evaluated volume in Plastimatch is eliminated (@gregsharp).  Regardless - I'll check it out!  Thanks.

**Comment by cpinter** [comment]
It actually makes a big difference. I just tried the standard IGRT test data and checking it increased pass rate from 80% to 94% (as I remember). So I suggest you do try it tomorrow. That said I should update the slicelets too. I'll do that now

**Comment by cpinter** [comment]
Are things working as expected? Can I close this issue?

**Comment by kmalexander5** [comment]
Seems to improve the comparison and produce more reasonable values.  I'd say this can be closed, as the back-end Plastimatch issues will be corrected on gitlab.  Will do more thorough testing when Plastimatch is updated.  Thanks @cpinter !

**Comment by cpinter** [comment]
Excellent, thanks! Yes, further changes need to happen at their respective places. Since this particular issue seems to be solved, I'm closing the ticket.
