### ISSUE TITLE
Could you please provides an example to reconstruct surface from some contours?

### ISSUE THREAD

**Issue by zhang-qiang-github** [SlicerRt/SlicerRT#118]
Could you please provides an example to reconstruct surface from some contours? The vtkPlanarContourToClosedSurfaceConversionRule seems to be a good choice, but I don't know how to run it. Moreover, the contours may not be parallel, and there may be a bifurcation. Could you please provide a demo about how to use the vtkPlanarContourToClosedSurfaceConversionRule? Thank you very much!

**Comment by cpinter** [comment]
I'd advise against using the converter function in itself. It is part of the PolySeg infrastructure (you can read more about it in [this PhD thesis](https://qspace.library.queensu.ca/handle/1974/26422)), which drives the Segmentations and Segment Editor modules in 3D Slicer.

So I'd simply recommend to use 3D Slicer. It does the conversion automatically when you load a DICOM-RT Structure Set. If you have further questions please contact us on the Slicer forum: https://discourse.slicer.org/
