### ISSUE TITLE
DVH Legend Shows Duplicate Titles

### ISSUE THREAD

**Issue by rpmumme** [SlicerRt/SlicerRT#127]
I was hoping you guys could help with this issue I've been having. I compute the DVH and display the plot, everything looks good, and I save the scene as a .mrb file. However, whenever I open the scene, the DVH legend shows 2 of everything. I have tried: 1) making sure all of the scenes are closed out before opening the Slicer program again, 2) toggling on and off the legend, 3) toggling on and off the DVH. 

Whenever I try deleting the chart and metrics table, I can recompute the DVH and display the correct legend. But after saving the scene and opening it again, the duplicates come back. Another thing I can do is toggle off and on each individual structure, which puts things back in place. However, these methods are pretty tedious and ideally I'm looking for the correct DVH legend to load up right away when the scene loads.

Legend before save:
![snip](https://user-images.githubusercontent.com/50175121/72383323-d73e9b00-36e0-11ea-85c0-420744b3f110.JPG)

Legend after save:
![snip2](https://user-images.githubusercontent.com/50175121/72383328-dad22200-36e0-11ea-904f-60e736c6dfdc.JPG)

**Comment by Sunderlandkyl** [comment]
I'll take a look at this, thank for reporting!

**Comment by cpinter** [comment]
There must be an automatic node creation triggering the addition of another node that should be disabled during scene import.

**Comment by Sunderlandkyl** [comment]
This turned out to be related to the reading of node references from the XML, which caused duplicate node references for each of the plotSeries in the chart node.
This pull request should fix the issue (https://github.com/Slicer/Slicer/pull/1304).

**Comment by rpmumme** [comment]
Thank you so much for the quick turnaround!

**Comment by rpmumme** [comment]
> This turned out to be related to the reading of node references from the XML, which caused duplicate node references for each of the plotSeries in the chart node.
> This pull request should fix the issue ([Slicer/Slicer#1304](https://github.com/Slicer/Slicer/pull/1304)).

I looked at the pull request and it looks like the branch hasn't been merged yet. Was there another issue that came up? Thank you for looking into this bug.

**Comment by Sunderlandkyl** [comment]
The pull request has now been merged. This should fix the issue.
