### ISSUE TITLE
Remove dependency from deprecated Slicer core modules

### ISSUE THREAD

**Issue by lassoan** [SlicerRt/SlicerRT#142]
We are planning to remove Slicer core modules that have been superseded by other modules.
https://discourse.slicer.org/t/removing-legacy-modules-in-slicer5/11371

This extension currently uses legacy "charts" infrastructure and vtkMRMLDoubleArray node. It should be upgraded to use plots and tables modules instead).

**Comment by cpinter** [comment]
Charts infrastructure has been removed and replaced by Plots in https://github.com/SlicerRt/SlicerRT/commit/8f9155f94399be71e747d3d45b1f6c4152caa139

**Comment by lassoan** [comment]
vtkMRMLDoubleArray is only used in MLC code, which will be addressed by https://github.com/SlicerRt/SlicerRT/issues/115
