### ISSUE TITLE
RT plan loading issues

### ISSUE THREAD

**Issue by cpinter** [SlicerRt/SlicerRT#145]
It takes around 10 minutes to load the Eclipse ENT test dataset. It only happens if I load the RT plan as well. It seems an unreasonably long time even if the plan is complex. In addition, it created dozens of beam nodes, with one MLC table in each, see below.

@MichaelColonel
1. Do you have an idea why it takes so long?
2. Is it a feature that so many beam nodes are created? By design we should have as many beam nodes as beams

![image](https://user-images.githubusercontent.com/1325980/82458642-d793dc00-9aae-11ea-8aba-cccbacf56629.png)

**Comment by MichaelColonel** [comment]
1. It definitely shouldn't load data so long, i will try to fix that issue ASAP.
2. If beam is intensity modulated, or some king of conformal in plan, then each beam can have multiple (dozens or hundreds) control points, and each control point is loaded as a separated beam. That is not a best idea, but there is nothing better.

The main reason why it take so much time, is the ImportExportLogic try to update (redraw) each beam when a new beam was added into the scene.

**Comment by cpinter** [comment]
Thank you for the quick answer! I appreciate you taking a look.

You're right, we did discuss the control points. Maybe they should be grouped to folders or somehow made easier to manage, because this very long list is not useful at all unfortunately. @gregsharp do you have any idea for this?

**Comment by lassoan** [comment]
It sounds like the most appropriate would be to store these control points in Sequence nodes. You can store thousands of nodes in one sequence node with small overhead. You can browse between sequence items using a slider or even replay them. You can expose one or more items from a sequence, and of course you have full access to all the nodes from code.

Sequences are now part of Slicer core (in Slicer-4.11) before that it was a separate extension.

**Comment by MichaelColonel** [comment]
As a temporary fix i can disable loading of multiple control points, so it will be only one control point per beam, as it was previously.

If batch processing is activated the loading is fast, but for the each beam one must manually invoke BeamTransformModified and BeamGeometryModified events (using Beams module) for proper visualization. For some reason BeamTransformModified event takes quite amount of time.

**Comment by cpinter** [comment]
Thanks @lassoan and @MichaelColonel! Let me take a closer look at the options before any quick fixes are made.

**Comment by cpinter** [comment]
In the latest version the loading time is similar to what we had before, and with the [sequences change](https://github.com/SlicerRt/SlicerRT/pull/147) the beam nodes are not overwhelming with the one node per control point, but there is one item for each beam.
