### ISSUE TITLE
Hope to export the dicom of the binary labelmap, or png

### ISSUE THREAD

**Issue by wwwwwuxueyu** [SlicerRt/SlicerRT#153]
After I converted RTss into a binary labelmap, I wanted to export the dicom of the binary labelmap. The result was a fast square in the middle, but there was no binary labelmap for the organization I wanted.

**Comment by cpinter** [comment]
> I wanted to export the dicom of the binary labelmap

What method did you use to export the labelmap to DICOM?

If you want to export a labelmap to DICOM, then the DICOM Segmentation Object is the appropriate format. If you install Reporting extension then you will be able to do that.

**Comment by cpinter** [comment]
Closing due to long inactivity.
