### ISSUE TITLE
Cannot load RT Plan (brachytherapy)

### ISSUE THREAD

**Issue by ferdymercury** [SlicerRt/SlicerRT#158]
In SlicerRT, I get an error when opening a DICOM dataset with an RT plan (brachytherapy).

`Could not load: 2: RTPLAN: Brachy Plan (plan) as a RT`

It would be a nice addition if brachy plans are supported, so that the seed position can be viewed as PointsOfInterest on top of the CT or US, both in the 2D and 3D views.

**Comment by cpinter** [comment]
What version of Slicer do you use? If older than 4.11 then please try with the latest preview, because brachy support was added after 4.10.2.

**Comment by ferdymercury** [comment]
Glad to hear! I was using 4.10.1
Thanks for the swift reply :)
