### ISSUE TITLE
Modules not showing up after fresh install

### ISSUE THREAD

**Issue by z-samuels** [SlicerRt/SlicerRT#159]
Slicer 4.10.2 r28257
SlicerRT 0.18 via extension manager
Windows 7 x64

After installing SlicerRT via extension manager (and restarting Slicer), only Plastimatch modules show up.

Extension manager lists SlicerRT as installed.

Same issue on similar computer.

**Comment by Sunderlandkyl** [comment]
I just tested uninstalling and reinstalling SlicerRT on 4.10.2, and the modules were installed successfully.

Are there any errors in the [log](https://www.slicer.org/wiki/Documentation/Nightly/SlicerApplication/ErrorLog#To_capture_the_entire_error_log_for_a_report)?

**Comment by z-samuels** [comment]
Fixed.

Log said that it couldn't find any of the .dll files, though they existed and were in the right location. Running Slicer as admin didn't change anything.

Installing the Visual C++ runtime referenced here (https://github.com/Slicer/Slicer/issues/4958) fixed the issue.
