### ISSUE TITLE
Integrate changes to Plastimatch

### ISSUE THREAD

**Issue by cpinter** [SlicerRt/SlicerRT#167]
Currently SlicerRT uses a fork of Plastimatch (https://gitlab.com/MichaelColonel/plastimatch). It would be much better integrating the changes to the Plastimatch repository and return to use that.

Re https://github.com/SlicerRt/SlicerRT/issues/164

**Comment by cpinter** [comment]
@MichaelColonel can you please look at this? Thank you!

**Comment by MichaelColonel** [comment]
Changes have been integrated in [Plastimatch master branch](https://gitlab.com/plastimatch/plastimatch/-/releases#1.9.3).
