### ISSUE TITLE
Installing SlicerRT makes Qt Designer crash

### ISSUE THREAD

**Issue by lassoan** [SlicerRt/SlicerRT#175]
After SlicerRT is installed, Qt designer cannot be started, because it crashes in qSlicerBeamsModuleWidgetsPlugins.dll.

Qt Designer instantiates custom widgets (via Qt widget plugins). Since in this case the application is not derived from qSlicerCoreApplication, all calls to qSlicerCoreApplication::application() return nullptr. This is a likely root cause of the crash. You need to add null-pointer checks to all qSlicerCoreApplication::application() calls (at least to those that are called during widget initialization).

See how we have just fixed a similar issue in Slicer core:
https://github.com/Slicer/Slicer/commit/30f347f9f1da97be48222cfbf12c91d887278fc7

**Comment by cpinter** [comment]
Designer now starts with SlicerRT. Thanks @MichaelColonel for the fix!
