### ISSUE TITLE
Cannot convert imported RTSTRUCT from planar contours to ribbon

### ISSUE THREAD

**Issue by lassoan** [SlicerRt/SlicerRT#177]
After importing an RTSTRUCT (for example, the ent phantom - https://downgit.github.io/#/home?url=https://github.com/SlicerRt/SlicerRtData/tree/master/eclipse-8.1.20-phantom-ent/Original), master representation of the segmentation is planar contour (correct) but when trying to create a ribbon representation (to be able to see the original contours in slice views), I get the error "Failed to convert ... to Ribbon model!

![image](https://user-images.githubusercontent.com/307929/106071225-f33a9200-60d3-11eb-99fe-82562e5b7bd6.png)

**Comment by lassoan** [comment]
@Sunderlandkyl could you please have a look at this? It makes it hard to investigate RTSTRUCT conversion issues. Thank you!

**Comment by Sunderlandkyl** [comment]
Sure, I'll take a look at it.

**Comment by Sunderlandkyl** [comment]
Should be fixed by https://github.com/Slicer/Slicer/pull/5411.

**Comment by Sunderlandkyl** [comment]
Fixed in https://github.com/Slicer/Slicer/commit/767551b4b8cf85f9d3193af1a5ff4ff8f3fdf728.
