### ISSUE TITLE
Only Export SumDose-File?

### ISSUE THREAD

**Issue by Kiragroh** [SlicerRt/SlicerRT#181]
Hi,
is it possible to only export a specific DICOM-File in some way? DICOM-Export seems only possible for complete DICOM-RT datasets (CT+RS+RP+RD).
I have many data sets of RS+RD+RE. I am using SlicerRT to build Sum-Dose-Files to analyze in python later. No CT (privacy reasons) and therefore no export of the sumDose-File I need.
My workaround so far: I used an empty dummy CT and changed the right DICOM-Tags every time to connect to each case.

**Comment by lassoan** [comment]
DICOM standard requires reference to the CT image. We need the CT image geometry to interpret the RT structure set (otherwise we can only guess the slice spacing).

**Comment by Kiragroh** [comment]
Thanks for the quick reply. I know that a complete DICOM-RT-dataset consists out of CT, RS-, RD- and RP-File. But after calculating Dose with CT, RS, + RP no CT should be necessary anymore in my experience.

Here is what I do not understand from your answer:
- slice spacing is not important for RT-Struct and RT-Dose. They have the same referenceFrame. Therefore I can work and do everything in SlicerRT without ever importing a CT. 
- All information for DICOM-Export should be available for the AccumulatedDose-File from the base Dose-File (only the PixelData has to be changed).

Can you please elaborate?
Thanks for your help

**Comment by cpinter** [comment]
> slice spacing is not important for RT-Struct and RT-Dose. They have the same referenceFrame

Contouring happens on the CT not the dose.

> All information for DICOM-Export should be available

SlicerRT only supports standard DICOM, and since the standard requires reference to the CT, so does SlicerRT. As you said using a dummy CT is a possible workaround.

**Comment by Kiragroh** [comment]
I understand but the RT-Struct is already there and I only want to export a Dose-File that can have a different resolution.

But I think for my few cases I will use the dummyCT. I build PixelData clearing to my anonymizer: https://github.com/Kiragroh/Kira_DICOM-RT-Anonymizer-MG

**Comment by cpinter** [comment]
Besides the considerations about only supporting standard DICOM, we also have technical constraints as well, as Plastimatch requires a CT in order to export the DICOM study, and it always exports it as a new study. So unfortunately there is no way to just export the dose without making profound changes in the code.

We are starting a maintenance project on Plastimatch these very days. We will start with more burning issues, but it is possible that we can also make export more flexible. Let us know if you would like to bring this case to the project owners. @gregsharp

**Comment by Kiragroh** [comment]
this sounds awesome. please do.

I first tried to only work with plastimatch-Standalone to accomplish my goal but found it not intuitive. Therefore I was impressed that I can do everything in SlicerRT but was sad that the last step (export) is not working for me.

Thanks for all the efforts

**Comment by cpinter** [comment]
> is not working for me

Contributions are always welcome! These are open-source projects that rely also on the community.

**Comment by Kiragroh** [comment]
Yeah of course. I will try to play with the SlicerRT code in a dummy Extension and will gladly contribute if helpful tools come from it.

Thanks again.

**Comment by cpinter** [comment]
Closing due to long inactivity.
