### ISSUE TITLE
The binary labelmap is cropped after using the batchprocessing.

### ISSUE THREAD

**Issue by itruonghai** [SlicerRt/SlicerRT#183]
Dear author, 
I try to convert all of my RTStruct file to the NIFTI ones. I try to use the BatchStructureSetConversion.py to convert, but the final labelmap is cropped (change the width and height). 
Here is my script
```
./Slicer --no-main-window --python-script ./test.py --input-folder input  --output-folder output -m

```
In my input folder, there are Dicom  and RTStruct (DicomRT) files. I already try to add the flag -r and split the input folder into dicom and dicomrt, but the labelmap is just a frame (although maintain the width and height). Hope you can help me to solve this problem.   
Here is the screenshot of labelmap. 
https://ibb.co/5cv62Lc    
https://ibb.co/7W6wL1Z
Note that the labelmap is 57x54x66 and the dicom is 512x512x132.

**Comment by cpinter** [comment]
Have you tried using a reference image?
See https://github.com/SlicerRt/SlicerRT/blob/master/BatchProcessing/_readme.txt#L9

**Comment by itruonghai** [comment]
> Have you tried using a reference image?
> See https://github.com/SlicerRt/SlicerRT/blob/master/BatchProcessing/_readme.txt#L9

I have already add flag -u into my script, but the .nii file at the end just have only 1 frame (the width and the height is 512x512). Can you have me to deal with that problem, sir?

**Comment by itruonghai** [comment]
@cpinter I see the volumn of refVolumn, and it has only 1 frame. I think that is the reason why when I activate flag -u, the final nii file have only 1 frame. 
My input folder is contain all of DCM file and DCM RT file, is this the reason?

**Comment by cpinter** [comment]
If you use a DICOM volume with one slice per volume, then you either need to make sure that all the slices are in the same folder as the RTSS file, or you need to specify the folder in which they are, see [here](https://github.com/SlicerRt/SlicerRT/blob/master/BatchProcessing/_readme.txt#L8).

**Comment by itruonghai** [comment]
@cpinter  My folder contains of all dicom image (per slice) with the prefix MR and a dicom rt with the prefix RS. You can see in the picture. How can I format it? https://ibb.co/vdVZyNX

**Comment by itruonghai** [comment]
@cpinter  any ideas for solving this problem, sir?
