### ISSUE TITLE
Can't export segmentation as Dicom RTStruct

### ISSUE THREAD

**Issue by Namng1210** [SlicerRt/SlicerRT#184]
Dear authors,
Everything seems to be really good when i exported it by hand and I've followed your instructions video of exporting RT-STRUCT file by right click at Study and choose Export to DICOM then click in RT struct and got the result as i want. 
<img width="660" alt="ui" src="https://user-images.githubusercontent.com/69883752/113840561-0005f100-97bb-11eb-9a66-5e50eb4507ef.png">
But when i was doing it in python script by the following code, after passing the studyID as parameter, i got the result return 'Exportable list contains no exportables'. Then, i have also tried to pass the segmentationID, but got another warning : 'Must export the primary anatomical (CT/MR) image'. How can i fix this problem ?      
<img width="672" alt="export" src="https://user-images.githubusercontent.com/69883752/113843983-3db84900-97be-11eb-9ae3-57485ea69b89.png">
Hope you reply me soon.

**Comment by cpinter** [comment]
In the above screenshot you export the study. In your script, you try to export only the segmentation, instead of the study, which would be the correct way.

We prefer questions asked in the [Slicer discourse forum](https://discourse.slicer.org/) for better visibility. Here please report bugs. Thank you.

**Comment by Namng1210** [comment]
Can you give me an instruction how to export study with DicomRTImportExportPlugin in Python Script. I've tried many ways but still can't make it. :(

**Comment by cpinter** [comment]
As I said you try to export the segmentation: `exporter.examineForExport(segmentationShItem)`
and instead you need to export the study: `exporter.examineForExport(studyShItem)`

**Comment by Namng1210** [comment]
<img width="677" alt="exportable" src="https://user-images.githubusercontent.com/69883752/113871567-3b191c00-97dd-11eb-8dc6-6de81a2ee3d3.png">
Yes i've also tried it but here is the result. When i checked source code it seems like dataNode can't read the studyID.. so it return nothing in exportables...

**Comment by cpinter** [comment]
I see. It seems you need to run the `examineForExport` function on all the series you want to export (the segmentation and the CT), collect the returned exportables in a list, and and pass that list for the `export` function.

At least this is what the GUI does, see
https://github.com/Slicer/Slicer/blob/master/Modules/Scripted/DICOMLib/Widgets/qSlicerDICOMExportDialog.cxx#L271

**Comment by Namng1210** [comment]
Oh great! It was actually worked! Thank you so much for your help!

**Comment by Namng1210** [comment]
OMG! It was actually worked ! Thanks you so much for helping for me <3

**Comment by cpinter** [comment]
Perfeft, thank you! Closing the issue then.

**Comment by roger-sun** [comment]
Hello,
I am kinda new with python. Can you explain to me how you manage to solve this issue? 

I tried to run the ExamineForExport function on the volume and the segmentations, then past them in a list for the export function, but it did not worked:

exporter = DicomRtImportExportPlugin.DicomRtImportExportPluginClass()
exportable1 = exporter.examineForExport(segmentationShItem)
exportable2 = exporter.examineForExport(referenceVolumeShItem)

for exp in exportable1:
exp.directory=outputFolder
for exp in exportable2:
exp.directory=outputFolder

exportables = [exportable1,exportable2]

exporter.export(exportables)
Traceback (most recent call last):
File “”, line 1, in
File “C:/Users/tmp/AppData/Roaming/NA-MIC/Extensions-29402/SlicerRT/lib/Slicer-4.11/qt-scripted-modules/DicomRtImportExportPlugin.py”, line 122, in export
exportable.copyToVtkExportable(vtkExportable)
AttributeError: ‘list’ object has no attribute ‘copyToVtkExportable’

thanks !
