### ISSUE TITLE
Problems when imported RT-Struct dicom folder into Varian Eclipse

### ISSUE THREAD

**Issue by Namng1210** [SlicerRt/SlicerRT#186]
Dear authors,
I have recently asked you guys about how to export to a segmentation nifti files into RT-Struct by python script and i was able to do it thanks to your instructions. But now, i'm facing new problems. 
**When i took the folder which was output by 3D Slicer to Varian Eclipse, i got a tons of error which was showed as below** 
![image](https://user-images.githubusercontent.com/69883752/116051395-c0884180-a6a2-11eb-88fa-657da488ccb6.png).
**And here is also the result when imported Auto_SS ( Segmentation rt-struct file which was created by 3D Slicer)**
![image](https://user-images.githubusercontent.com/69883752/116052410-c9c5de00-a6a3-11eb-9700-a166f811dd37.png)
Can you show me how to deal with these problems ?
Hope you reply me soon.

**Comment by ferdymercury** [comment]
When you convert from NIFTI to RTstruct, do you set all the mandatory DICOM tags in your Python script?

It seems that the .dcm output files are missing mandatory tags, see http://dicom.nema.org/dicom/2013/output/chtml/part05/sect_7.4.html
like for example
MR Acquisition Type which is "Type 2"
You could fix that by hand opening the .dcm files and adding in the missing mandatory tags if you known them.

What 3DSlicer version are you using?

**Comment by lassoan** [comment]
@Namng1210  Have you segmented an MRI image and tried to import that into Eclipse?

**Comment by cpinter** [comment]
Closing due to long inactivity.
