### ISSUE TITLE
vtkCollisionDetectionFilter out of sync with VTK

### ISSUE THREAD

**Issue by ferdymercury** [SlicerRt/SlicerRT#195]
SlicerRT has an outdated vtkCollisionDetectionFilter class, that is now natively part of VTK. It would be nice to migrate it to VTK to get also the latest bug fixes and reduce maintenance effort here in SlicerRT. See e.g. https://gitlab.kitware.com/vtk/vtk/-/issues/18298
Thanks!

**Comment by lassoan** [comment]
Thanks for the ping. Yes, we managed to get this filter into VTK with Bill, so we can exclude it from Slicer-4.13 builds now. I'll submit a pull request soon.
