### ISSUE TITLE
slicer RT make radiotherapy plan

### ISSUE THREAD

**Issue by zhuyingying1234** [SlicerRt/SlicerRT#209]
slicerRT could be used for IMRT or VMAT ? maybe a Forward intensity plan?

**Comment by lassoan** [comment]
This issue tracker is used for tracking problems and enhancements. Would you mind posting your question to the Slicer forum and post the link here? Thank you.

**Comment by zhuyingying1234** [comment]
Hello, because I want to do some research on radiotherapy plan, I would like to ask whether this software can only be used for the design of radiotherapy plan with forward intensity modulated therapy.Thanks for answering my question

**Comment by zhuyingying1234** [comment]
of course not

**Comment by cpinter** [comment]
The Slicer forum where usability questions should be posted is here: https://discourse.slicer.org/
Thanks!

**Comment by zhuyingying1234** [comment]
<img width="911" alt="截屏2022-03-26 上午9 33 03的副本 上午9 35 42" src="https://user-images.githubusercontent.com/102264882/160220547-5e9fbc2a-b649-4c36-887c-04a0963a8d48.png">How to convert the Isidose curve unit MU to Gy？
<img width="439" alt="截屏2022-03-26 上午9 39 19" src="https://user-images.githubusercontent.com/102264882/160220601-dfce68ff-36a0-400d-a92e-5d1ebd99eedf.png">Why DVH is a few tenths of Gy, where is the problem？ 
because I am a novice, in the use of a lot of do not understand, thanks for guidance.

**Comment by cpinter** [comment]
The Slicer forum where usability questions should be posted is here: https://discourse.slicer.org/
Thanks!
