### ISSUE TITLE
Plastimatch changes for C++17 compilation under Linux and Mac

### ISSUE THREAD

**Issue by MichaelColonel** [SlicerRt/SlicerRT#213]
There are still problems for Mac and Linux compilation after C++17 update

Mac - https://slicer.cdash.org/viewBuildError.php?buildid=2734563
Linux - https://slicer.cdash.org/viewBuildError.php?buildid=2734411

The error is the same - dynamic exception specifications doesn't allowed in C++17.

I have tested under Linux.

Files to modify:
1. [itkVelocityFieldLieBracketFilter.h](https://gitlab.com/plastimatch/plastimatch/-/blob/master/libs/demons_itk_insight/LOGDomainDemons/itkVelocityFieldLieBracketFilter.h#L82). Already modified in Plastimatch master
2. [itkVelocityFieldLieBracketFilter.txx](https://gitlab.com/plastimatch/plastimatch/-/blob/master/libs/demons_itk_insight/LOGDomainDemons/itkVelocityFieldLieBracketFilter.txx#L45). Already modified in Plastimatch master

3. [matrix.h](https://gitlab.com/plastimatch/plastimatch/-/blob/master/libs/dlib-19.1/dlib/matrix/matrix.h#L1754). Unmodified in Plastimatch master

I think these throws can be hidden in preprocessor definition, rather than just deleted. IMHO.

**Comment by Sunderlandkyl** [comment]
I've created an updated [plastimatch branch](https://github.com/SlicerRt/plastimatch/tree/slicerrt-1.9.3-2022.06.15-77b40bd3) from the latest version + removed the throw from matrix.h. Everything compiles correctly on Windows.

Can you confirm that the update fixes the issue on Linux?

**Comment by MichaelColonel** [comment]
Compilation and tests are OK!

**Comment by MichaelColonel** [comment]
For Mac there is another [issue](https://slicer.cdash.org/viewBuildError.php?buildid=2735473). The register specifier must be removed. On linux with GCC-11.2 it's just a warning.

**Comment by jamesobutler** [comment]
There are no more build errors as of https://github.com/SlicerRt/SlicerRT/commit/8a7330502e9e0daa327dad6a9552e987aa837a77.
