### ISSUE TITLE
Isodose calculation replaces previously created isodose

### ISSUE THREAD

**Issue by ywatana1** [SlicerRt/SlicerRT#224]
With older versions, I could overlay isodose lines of two RTDOSE files using the isodose tool. But, with the latest version 5.3.0-2022-11-26, I cannot do it anymore. It replaces the isodose line plot when I generate isodose lines after changing the RTDOSE file.

**Comment by MichaelColonel** [comment]
Dear @ywatana1,

Do you need one isodose lines model node per RTDOSE volume or multiple isodose model nodes?

**Comment by ywatana1** [comment]
I am not sure what you mean by "isodose model nodes". What I need it is to overlay a set of isodose lines from RTDOSE #2 on the dose from RTDOSE#1, resulting in two sets of isodose lines on one display. I use this function to compare two dose calculation methods.

**Comment by MichaelColonel** [comment]
Possible fix is ready. PR #225.

**Comment by cpinter** [comment]
Integrated. @ywatana1 please test tomorrow (when the Slicer build system provides a new build that includes this change) and close if it works as expected. Thank you!

**Comment by ywatana1** [comment]
Great. The functionality back on the 1/5/2023 version. 
If we could select different line types of each set, it would be even better. 
Thank you very much.

**Comment by MichaelColonel** [comment]
Good, that it works as it should.

> If we could select different line types of each set, it would be even better.

I will think how that feature can be implemented.
