### ISSUE TITLE
RTSTRUCT not loaded Slicer5.2.2, SlicertRT from 02/22/23

### ISSUE THREAD

**Issue by katerinachytra** [SlicerRt/SlicerRT#232]
RTSTRUCT is not loaded. After clicking on Examine button in Advanced option, nothing is shown.
<img width="960" alt="SlicerRTSTRUCTloadproblem" src="https://github.com/SlicerRt/SlicerRT/assets/32932363/00f7778b-b9b9-4476-bdb8-d7e5cf9545bd">

**Comment by lassoan** [comment]
Have you installed SlicerRT extension? Do you see any errors in the application log?

**Comment by cpinter** [comment]
This issue has been apparently abandoned by the reporter, closing it.
