### ISSUE TITLE
Set required DICOM reference between dose and CT

### ISSUE THREAD

**Issue by cpinter** [SlicerRt/SlicerRT#233]
See https://discourse.slicer.org/t/dicom-rt-dose-export-error-patient-uid/31285

**Comment by MichaelColonel** [comment]
I want to fix that issue by adding ReferencedInstanceUID from CT volume node, with corresponding UID, within qSlicerSubjectHierarchyRtDoseVolumePlugin.

For example both CT and a newly created dose volume are children of some Study Item, and the dose volume doesn't know anything about CT, Study or RTPLAN (no attributes).
What is the best way to get a Subject Hierarchy Item of the CT volume node, only by checking modality attribute of the CT volume node item?

**Comment by cpinter** [comment]
Thanks @MichaelColonel !

> What is the best way to get a Subject Hierarchy Item of the CT volume node, only by checking modality attribute of the CT volume node item?

If you have access to the CT volume node then getting the SH item is as simple as
`shNode.GetItemByDataNode(ctVolumeNode)`
unless I misunderstand the question.
