### ISSUE TITLE
Fix patient support rotation angle to fixed reference

### ISSUE THREAD

**Issue by MichaelColonel** [SlicerRt/SlicerRT#235]
There is a new bug in vtkSlicerIECTransformLogic. Couch angle rotation between patient support rotation and fixed reference is calculated in wrong direction. The result of this bug is incorrect beam orientation.

[Current](https://github.com/SlicerRt/SlicerRT/blob/master/Beams/Logic/vtkSlicerIECTransformLogic.cxx#L263)
``` c++
this->UpdatePatientSupportRotationToFixedReferenceTransform(-1.0 * beamNode->GetCouchAngle());
```
[Test data](https://github.com/SlicerRt/SlicerRtData/tree/master/xio-4.64-phantom-prostate-beams-allnonzero)

![Screenshot_before](https://github.com/SlicerRt/SlicerRT/assets/3785912/12ba2951-c334-47b3-9347-c48640725f74)

Should be
``` c++
this->UpdatePatientSupportRotationToFixedReferenceTransform(beamNode->GetCouchAngle());
```

![Screenshot_after](https://github.com/SlicerRt/SlicerRT/assets/3785912/5c8e3fce-9f41-4be0-a8e1-6bdaa48fa5d9)

**Comment by ferdymercury** [comment]
Thanks for finding out!
@cpinter this can be closed now
