### ISSUE TITLE
Resolving SlicerRT Module Issues

### ISSUE THREAD

**Issue by mshlzhrn** [SlicerRt/SlicerRT#239]
I need assistance with the SlicerRT extension. Previously, I was using an older version of 3D Slicer with SlicerRT and all modules, including Beams, External Beam Planning, Segment Comparison, and Segment Morphology, were functioning correctly. However, after updating to 3D Slicer version 5.6.0 and reinstalling SlicerRT, I noticed that these specific modules are no longer available. Any guidance or suggestions would be greatly appreciated.

**Comment by Sunderlandkyl** [comment]
Can you attach a log file?

**Comment by mshlzhrn** [comment]
Thank you. Please find attached file. 

[Python Console.txt](https://github.com/SlicerRt/SlicerRT/files/13603241/Python.Console.txt)

**Comment by Sunderlandkyl** [comment]
Looks like this is a known issue for some extensions on MacOS: https://discourse.slicer.org/t/the-dependency-dicomrtimportexport-failed-to-be-loaded-slicerrt-issue/32073.

**Comment by mshlzhrn** [comment]
Thank you, Kyle. I rolled back to 3D Slicer version 5.2.2 and all SlicerRT modules are working fine now.
