### ISSUE TITLE
Images in Contributors page on Homepage are not showing

### ISSUE THREAD

**Issue by haphantran** [SlicerRt/SlicerRT#245]
Hi team,
I found below issue on your home page. All the images link are dead in [Contributors.md](https://github.com/SlicerRt/slicerrt.github.com/blob/master/Contributors.md). I can't open the issue on the other repo (slicerrt.github.com), so I open this here. Hopefully this can get to the team behind SlicerRT.
<img width="1240" alt="image" src="https://github.com/SlicerRt/SlicerRT/assets/47532906/0cf7253d-4172-418a-a7ac-aeeb02a037f4">
Thank you,
HaPhan.

**Comment by Sunderlandkyl** [comment]
Thanks! I've updated the logo urls in Contributors.md.
