### ISSUE TITLE
Add option in Room's Eye view for camera staying in the fixed system

### ISSUE THREAD

**Issue by cpinter** [SlicerRt/SlicerRT#246]
In SlicerRT, the reference coordinate system is the patient instead of the fixed system that the IEC standard defines. This results in the linac body moving when we change table top parameters, instead of the table moving. This is fine in Slicer, because the center of any workflow is the patient. However, it would be useful to add a mode in which the camera is moved dynamically in a way that the Fixed system stays still when such transformations are applied that move it.

**Comment by MichaelColonel** [comment]
It should be a fixed camera, or user can change position and orientation of camera in FixedReference frame?

**Comment by cpinter** [comment]
Sorry I don't understand the question. In any case this was the key point in my suggestion:
"add a mode in which the camera is moved **dynamically** in a way that the **Fixed system stays still** when such transformations are applied that move it"

**Comment by MichaelColonel** [comment]
Of course camera position will observe (or follow) fixed system transform in order to update camera orientation so it will stay still within fixed system. I mean it should be a one camera within fixed system (predefined), or user will define initial position of the camera?

**Comment by cpinter** [comment]
I don't think any definition is needed, the current camera, whatever it is, can be used. When the user changes the patient support rotation angle, for example, the REV module should rotate the camera accordingly.

**Comment by ferdymercury** [comment]
This is awesome, thanks @MichaelColonel for the implementation. I guess this issue can now be closed?
