### ISSUE TITLE
adding save option

### ISSUE THREAD

**Issue by YazdanSalimi** [SlicerRt/SlicerRT#260]
Hello, thank you for the great versatile software. I updated the save function for saving the segmentations to write the segment name and segmentation name on the file.  maybe usefull for someone. 
thanks
    segmentationNodes = slicer.util.getNodesByClass('vtkMRMLSegmentationNode')
    segmentationNodeNames = [node.GetName() for node in segmentationNodes]
    for segmentationNode, segmentationNode_name in zip(segmentationNodes, segmentationNodeNames):
          segmentation = segmentationNode.GetSegmentation()
          if not os.path.exists(output_folder):
              os.makedirs(output_folder)
          for i in range(segmentation.GetNumberOfSegments()):
              segmentID = segmentation.GetNthSegmentID(i)
              segmentName = segmentation.GetSegment(segmentID).GetName()
             
              labelmapNode = slicer.mrmlScene.AddNewNodeByClass('vtkMRMLLabelMapVolumeNode', segmentName)
              slicer.modules.segmentations.logic().ExportSegmentsToLabelmapNode(
                  segmentationNode, [segmentID], labelmapNode)
           
              filePath = os.path.join(output_folder, f"{segmentationNode_name}---{segmentName}.nii.gz")
              slicer.util.saveNode(labelmapNode, filePath)
              # print(f"Saved: {filePath}")
              slicer.mrmlScene.RemoveNode(labelmapNode)

**Comment by cpinter** [comment]
Great, thank you! Is there anything we need to do in respect? I don't see anything actionable from our side so closing the issue but feel free to reopen it if I misinterpret.
