### ISSUE TITLE
Update DVH module to use tables and plot views

### ISSUE THREAD

**Issue by cpinter** [SlicerRt/SlicerRT#76]
Tables is a feature that is now mature enough to replace the manually developed table feature in the DVH module. It would make sense to update the DVH module to use that, because Tables is continually improved and maintained, and it can better deal with the complex DVH metadata (for example columns can  specify metadata and we don't need to extract it from the header strings).

Also, plot view can be used, because it can display table nodes directly. May need to keep both types of visualization (charts look better, e.g. for publication).

- [x] Update tests
- [x] Update wiki page and screenshot

**Comment by cpinter** [comment]
May be related to https://github.com/SlicerRt/SlicerRT/issues/2

**Comment by lassoan** [comment]
> May need to keep both types of visualization (charts look better, e.g. for publication).

We should be able to make the new plot infrastructure display as nice graphics as jqPlot. Is there anything specific that does not look nice in the new plots?

**Comment by cpinter** [comment]
This is not my opinion, I heard it from others, that jqplot gives a generally more appealing image. I guess it's the not all-white background, the smooth lines, but not sure.
