### ISSUE TITLE
Plastimatch build error with Qt5/VTK8 on Mac

### ISSUE THREAD

**Issue by cpinter** [SlicerRt/SlicerRT#79]
/Users/cpinter/Devel/_Experimental/SlicerRT_Q5/Plastimatch/src/plastimatch/base/rpl_volume_lut.cxx:142:42: error: 
      non-constant-expression cannot be narrowed from type 'double' to 'float' in initializer list [-Wc++11-narrowing]
                float ap_xy_float[2] = { ap_xy[0], ap_xy[1] };
                                         ^~~~~~~~
/Users/cpinter/Devel/_Experimental/SlicerRT_Q5/Plastimatch/src/plastimatch/base/rpl_volume_lut.cxx:142:42: note: insert an explicit
      cast to silence this issue
                float ap_xy_float[2] = { ap_xy[0], ap_xy[1] };
                                         ^~~~~~~~
                                         static_cast<float>( )
/Users/cpinter/Devel/_Experimental/SlicerRT_Q5/Plastimatch/src/plastimatch/base/rpl_volume_lut.cxx:142:52: error: 
      non-constant-expression cannot be narrowed from type 'double' to 'float' in initializer list [-Wc++11-narrowing]
                float ap_xy_float[2] = { ap_xy[0], ap_xy[1] };
                                                   ^~~~~~~~
/Users/cpinter/Devel/_Experimental/SlicerRT_Q5/Plastimatch/src/plastimatch/base/rpl_volume_lut.cxx:142:52: note: insert an explicit
      cast to silence this issue
                float ap_xy_float[2] = { ap_xy[0], ap_xy[1] };
                                                   ^~~~~~~~
                                                   static_cast<float>( )
2 errors generated.

**Comment by cpinter** [comment]
I applied a fix, will be back with a PR if it proves to work. I adde static_cast<float> in line 142. Or we may change the type of ap_xy to float in the first place. @gregsharp what do you think?

**Comment by cpinter** [comment]
More of the same after the static_cast fix:

/Users/cpinter/Devel/_Experimental/SlicerRT_Q5/Plastimatch/src/plastimatch/dose/dose_volume_functions.cxx:274:26: error: 
      non-constant-expression cannot be narrowed from type 'plm_long' (aka 'long long') to 'int' in initializer list
      [-Wc++11-narrowing]
        int ap_dim[2] = {beam->get_aperture()->get_dim(0),beam->get_aperture()->get_dim(1)};
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/cpinter/Devel/_Experimental/SlicerRT_Q5/Plastimatch/src/plastimatch/dose/dose_volume_functions.cxx:274:26: note: insert an
      explicit cast to silence this issue
        int ap_dim[2] = {beam->get_aperture()->get_dim(0),beam->get_aperture()->get_dim(1)};
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                         static_cast<int>(               )
/Users/cpinter/Devel/_Experimental/SlicerRT_Q5/Plastimatch/src/plastimatch/dose/dose_volume_functions.cxx:274:59: error: 
      non-constant-expression cannot be narrowed from type 'plm_long' (aka 'long long') to 'int' in initializer list
      [-Wc++11-narrowing]
        int ap_dim[2] = {beam->get_aperture()->get_dim(0),beam->get_aperture()->get_dim(1)};
                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/cpinter/Devel/_Experimental/SlicerRT_Q5/Plastimatch/src/plastimatch/dose/dose_volume_functions.cxx:274:59: note: insert an
      explicit cast to silence this issue
        int ap_dim[2] = {beam->get_aperture()->get_dim(0),beam->get_aperture()->get_dim(1)};
                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                          static_cast<int>(               )
/Users/cpinter/Devel/_Experimental/SlicerRT_Q5/Plastimatch/src/plastimatch/dose/dose_volume_functions.cxx:297:26: error: 
      non-constant-expression cannot be narrowed from type 'plm_long' (aka 'long long') to 'int' in initializer list
      [-Wc++11-narrowing]
        int ap_dim[2] = {beam->get_aperture()->get_dim(0),beam->get_aperture()->get_dim(1)};
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/cpinter/Devel/_Experimental/SlicerRT_Q5/Plastimatch/src/plastimatch/dose/dose_volume_functions.cxx:297:26: note: insert an
      explicit cast to silence this issue
        int ap_dim[2] = {beam->get_aperture()->get_dim(0),beam->get_aperture()->get_dim(1)};
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                         static_cast<int>(               )
/Users/cpinter/Devel/_Experimental/SlicerRT_Q5/Plastimatch/src/plastimatch/dose/dose_volume_functions.cxx:297:59: error: 
      non-constant-expression cannot be narrowed from type 'plm_long' (aka 'long long') to 'int' in initializer list
      [-Wc++11-narrowing]
        int ap_dim[2] = {beam->get_aperture()->get_dim(0),beam->get_aperture()->get_dim(1)};
                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/cpinter/Devel/_Experimental/SlicerRT_Q5/Plastimatch/src/plastimatch/dose/dose_volume_functions.cxx:297:59: note: insert an
      explicit cast to silence this issue
        int ap_dim[2] = {beam->get_aperture()->get_dim(0),beam->get_aperture()->get_dim(1)};
                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                          static_cast<int>(               )

**Comment by cpinter** [comment]
Even more... I'll try to go through each error and fix it.

**Comment by cpinter** [comment]
@gregsharp I fixed all of them. I believe I haven't contributed since the GitLab switch. What's the best way? Register to GitLab, fork, etc. just like GitHub?

**Comment by cpinter** [comment]
Submitted a merge request, please merge so that SlicerRT builds with Qt5 and VTK8 (C++11)
https://gitlab.com/plastimatch/plastimatch/merge_requests/7

We'll also need to update the Plastimatch hash in SlicerRT once the merge is complete. Thanks!

**Comment by gregsharp** [comment]
Merged with minor fix.  Bumped plastimatch git hash in [1].  Tested on linux, works for me.  Let me know.  Thanks Csaba!

[1] https://github.com/SlicerRt/SlicerRT/commit/345761ebe58db398c9ce8f19fc46c55ca5273c17

**Comment by gregsharp** [comment]
PS: You have a gitlab account, and have full permissions on plastimatch project.  Feel free to commit directly if that is easier.

**Comment by cpinter** [comment]
Thank you! You probbaly have told me all this but it was so long ago I forgot. I'll commit the straightforward stuff directly in the future.
