### ISSUE TITLE
Index out of bounds in vtkPlanarContourToClosedSurfaceConversionRule

### ISSUE THREAD

**Issue by jarzec** [SlicerRt/SlicerRT#87]
In [vtkPlanarContourToClosedSurfaceConversionRule.cxx](https://github.com/SlicerRt/SlicerRT/blob/master/DicomRtImportExport/ConversionRules/vtkPlanarContourToClosedSurfaceConversionRule.cxx)
Line 1762 is:
`      if (outputLineIds->GetId(0) != outputLineIds->GetId(outputLineIds->GetNumberOfIds()))`
and should likely become:
`      if (outputLineIds->GetId(0) != outputLineIds->GetId(outputLineIds->GetNumberOfIds() - 1))`

**Comment by Sunderlandkyl** [comment]
Thanks for reporting this, I'll take a look at it!
