### ISSUE TITLE
Unable to convert a mhd file into RT Dose

### ISSUE THREAD

**Issue by lassoan** [SlicerRt/SlicerRT#88]
Issue migrated from https://issues.slicer.org/view.php?id=4486

Reporter: yodaFOx

Hi everybody,
I would like to convert some mhd file into RT Dose. So far, I have succefully converted when these mhd were placed into a study hierarchy (NewSubject then NewStudy). However, since I have updated my Slicer version (to 4.8) running through MacOS, I always wind up with the following message: "The volume must be under a study in order to be converted to dose. Please drag&drop the volume under a study. If there is no study, it can be created under a subject. Consult the help window for more details." despite the fact I have well placed the mhd files into the study hierarchy (I sucessfully proceeded like this a thousand time in the previous versions).
Someone have spotted the same bug as well?
Thanks in advance,
Jonathan

In the Data module, Subject hierarchy tab:
- create new subject
- create child study
- place the mhd files into the hierarchy
- right click and Convert to RT dose volume
- the error message appears

**Comment by cpinter** [comment]
I wasn't able to reproduce the issue based on the reporter's description. Further guidance would be required to proceed.

**Comment by cpinter** [comment]
Still not able to reproduce it. In absence of any follow-up in the past half year, I'm closing this issue.
