### ISSUE TITLE
SlicerRT nightly build failure

### ISSUE THREAD

**Issue by tavaughan** [SlicerRt/SlicerRT#92]
Windows:
http://slicer.cdash.org/viewBuildError.php?buildid=1377648

Linux:
http://slicer.cdash.org/viewBuildError.php?buildid=1377552

**Comment by cpinter** [comment]
Thanks, Thomas! Probably related to the recent ITK update.
@gregsharp Can you please look at it? The error is about a missing GetSeriesHelper function in itk::GDCMSeriesFileNames.

**Comment by cpinter** [comment]
Fixed in https://github.com/SlicerRt/SlicerRT/commit/e33678fde5a44881e19c3b51460bb73fee93a9fe
