### ISSUE TITLE
Internal Error when using External Beam Planning Module

### ISSUE THREAD

**Issue by MarcoSerna** [SlicerRt/SlicerRT#95]
I am loading DICOM CT and RT files and am attempting to create a plan and dosage using the External Beam Planning module.
My process:
   -Create New RT Plan
   -Select Reference Volume
   -Select Structure Set
   -Using default Points of interest
   -Create new RT Dose Volume
   -Created a single beam with default settings

After clicking 'Calculate Dose' and 'Internal Error' popup occurs stating, "Exception thrown in event: Error: unhandled conversion from PLM_IMG_TYPE_ITK_DOUBLE to itk_short.

![image](https://user-images.githubusercontent.com/16005832/48649071-466a1380-e9a6-11e8-99cf-ca705c772a8c.png)

**Comment by MarcoSerna** [comment]
Update: This error only occurs when using the Plastimatch Proton Dose engine. When using Mock Random or Mock Python, the beam intensity is shown, but the dose distribution among the structures in not shown.

![beamimage](https://user-images.githubusercontent.com/16005832/48648820-9b595a00-e9a5-11e8-994e-434755746613.PNG)
![beamimage1](https://user-images.githubusercontent.com/16005832/48648821-9b595a00-e9a5-11e8-944b-654b442ff300.PNG)
![beamimage2](https://user-images.githubusercontent.com/16005832/48648822-9bf1f080-e9a5-11e8-930f-f205db31c688.PNG)
![beamimage3](https://user-images.githubusercontent.com/16005832/48648823-9bf1f080-e9a5-11e8-9a50-cbe2196df125.PNG)

**Comment by cpinter** [comment]
Thanks for reporting the issue! It seems to me that your specific dataset is causing problems in the internals of Plastimatch when calculating the proton dose. If the data you use does not contain sensitive information, the biggest help would be to share the Slicer scene with us that you have before clicking Calculate dose. Then we could debug the problem and potentially fix it. Thanks!

@gregsharp Please follow this discussion in case you have an idea.

**Comment by MarcoSerna** [comment]
This is a sample series I found among Slicer RT folders, I just added a quick segmentation of the head, brain and a mass. I will send both CT slices and RT file, along with the original version. I appreciate the response!
[My_Segmentation.zip](https://github.com/SlicerRt/SlicerRT/files/2591119/My_Segmentation.zip)
[rtog-head-and-neck-cetuximab.zip](https://github.com/SlicerRt/SlicerRT/files/2591115/rtog-head-and-neck-cetuximab.zip)

**Comment by MarcoSerna** [comment]
I should also mention that I cannot replicate the dose results from that head-and-neck sample.

**Comment by cpinter** [comment]
Thanks for the data! I'll try to investigate this soon, and will also contact @gregsharp about the proton engine details.

**Comment by cpinter** [comment]
I just had time to test this, sorry for the delay.

It's very strange that on my computer with the latest versions the dose is calculated without problems:

![image](https://user-images.githubusercontent.com/1325980/48959043-d96bf600-ef30-11e8-8b8d-28e736448965.png)

If you didn't use the latest nightly can you please try with that one?
Here's the latest windows release: http://slicer.kitware.com/midas3/api/rest?method=midas.bitstream.download&name=Slicer-4.11.0-2018-11-22-win-amd64.exe&checksum=9394bfee3a3ccd082f7e80d9bc8d937d

**Comment by MarcoSerna** [comment]
I realized my mistake, I forgot to do a general registration for the CT images. I appreciate your assistance!

**Comment by cpinter** [comment]
Thanks for confirming! Let us know if you need any help.

**Comment by MarcoSerna** [comment]
I was wondering if you needed to do a registration of the images before running External Beam Planning for the proton dose engine?
